# Generated by Django 2.2.6 on 2019-10-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slingshot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('org_desc', models.TextField(blank=True, max_length=500)),
                ('org_logo', models.ImageField(blank=True, upload_to='media/organazition/profile-pics')),
                ('org_email', models.CharField(blank=True, max_length=60)),
                ('org_website', models.CharField(blank=True, max_length=60)),
                ('org_insta', models.CharField(blank=True, max_length=60)),
                ('org_twitter', models.CharField(blank=True, max_length=60)),
                ('org_twitch', models.CharField(blank=True, max_length=60)),
                ('org_youtube', models.CharField(blank=True, max_length=60)),
                ('org_discord', models.CharField(blank=True, max_length=60)),
                ('org_owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='slingshot.User')),
            ],
        ),
    ]
