# Generated by Django 2.2.6 on 2019-11-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0003_notification_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_notification', to='slingshot.Team'),
        ),
    ]
