# Generated by Django 2.2.6 on 2019-12-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0004_auto_20191109_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created',)},
        ),
    ]
