# Generated by Django 2.2.6 on 2019-10-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=60)),
                ('following_name', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, default='', upload_to='user/profile')),
                ('bio', models.TextField(blank=True, default='', max_length=300)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('wallet', models.PositiveIntegerField(blank=True, default=0)),
                ('earnings', models.PositiveIntegerField(blank=True, default=0)),
                ('wins', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('loss', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('tie', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, default='', upload_to='team/profile')),
                ('captain', models.CharField(max_length=50)),
                ('wallet', models.PositiveIntegerField(blank=True, default=0)),
                ('earnings', models.PositiveIntegerField(blank=True, default=0)),
                ('wins', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('loss', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('tie', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('members', models.ManyToManyField(blank=True, related_name='members', to='slingshot.User')),
            ],
        ),
    ]
