# Generated by Django 2.2.6 on 2019-10-31 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='following_name',
        ),
        migrations.RemoveField(
            model_name='following',
            name='user_name',
        ),
        migrations.AddField(
            model_name='following',
            name='followed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to='slingshot.User'),
        ),
        migrations.AddField(
            model_name='following',
            name='following_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to='slingshot.User'),
        ),
        migrations.AddField(
            model_name='following',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
