# Generated by Django 2.2.6 on 2020-02-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
