# Generated by Django 2.2.6 on 2019-10-31 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0002_auto_20191031_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
