# Generated by Django 2.2.6 on 2020-02-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0002_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
