# Generated by Django 2.2.6 on 2019-11-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0005_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_back',
            field=models.ImageField(blank=True, upload_to='user/profile'),
        ),
    ]
