# Generated by Django 2.2.6 on 2019-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0006_user_profile_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_banner',
            field=models.ImageField(blank=True, default='', upload_to='team/profile'),
        ),
    ]
