# Generated by Django 2.2.6 on 2019-11-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0007_team_team_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
