# Generated by Django 2.2.6 on 2019-12-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0008_team_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followed_by', to='slingshot.User'),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
