# Generated by Django 2.2.6 on 2020-01-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0009_auto_20191207_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='team/profile/default.jpg', upload_to='team/profile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tie',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user/profile/default.jpg', upload_to='user/profile'),
        ),
    ]
