# Generated by Django 2.2.6 on 2020-01-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0010_auto_20200121_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tie',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
