# Generated by Django 2.2.6 on 2020-01-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0011_auto_20200123_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kills',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
