# Generated by Django 2.2.6 on 2020-02-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0014_auto_20200203_0542'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='slingshot_u_usernam_ccacb7_idx'),
        ),
    ]
