# Generated by Django 2.2.6 on 2019-10-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=60)),
                ('bg_image', models.ImageField(blank=True, upload_to='games/bg_images')),
                ('card_image', models.ImageField(blank=True, upload_to='games/card_images')),
                ('water_image', models.ImageField(blank=True, upload_to='games/water_marks')),
                ('wins', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('loss', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('tie', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
        ),
    ]
