# Generated by Django 2.2.6 on 2019-10-25 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tie',
        ),
        migrations.RemoveField(
            model_name='game',
            name='wins',
        ),
    ]
