# Generated by Django 2.2.6 on 2020-02-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='test',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
