# Generated by Django 2.2.6 on 2020-02-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0002_scorecard_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreCard',
        ),
    ]
