# Generated by Django 2.2.6 on 2020-02-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0002_scorecard_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='test',
        ),
    ]
