# Generated by Django 2.2.6 on 2019-10-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0001_initial'),
        ('tourney', '0002_auto_20191025_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_validate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.ManyToManyField(blank=True, related_name='game', to='tourney.Game')),
                ('userId', models.ManyToManyField(blank=True, related_name='player', to='slingshot.User')),
            ],
        ),
    ]
