# Generated by Django 2.2.6 on 2019-10-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0003_game_validate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game_validate',
        ),
    ]
