# Generated by Django 2.2.6 on 2020-02-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0001_initial'),
        ('tourney', '0004_scorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='in_game_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='loss',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_score_card', to='tourney.Match'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='solo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solo_score_card', to='slingshot.User'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_score_card', to='slingshot.Team'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='tie',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='kills',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
