# Generated by Django 2.2.6 on 2019-10-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0006_delete_game_validate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_validate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, max_length=60)),
                ('gameName', models.CharField(blank=True, max_length=60)),
                ('gameId', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
