# Generated by Django 2.2.6 on 2019-10-26 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0001_initial'),
        ('tourney', '0011_game_validate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('banner', models.ImageField(blank=True, upload_to='tournament/banners')),
                ('prize_pool', models.PositiveIntegerField(blank=True, default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=True)),
                ('rules', models.TextField(blank=True, max_length=500)),
                ('contact', models.TextField(blank=True, max_length=400)),
                ('schedule', models.TextField(blank=True, max_length=600)),
                ('tour_type', models.CharField(blank=True, max_length=60)),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='slingshot.User')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='slingshot.Team')),
                ('tour_game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_game', to='tourney.Game')),
                ('winner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='slingshot.User')),
            ],
        ),
    ]
