# Generated by Django 2.2.6 on 2019-10-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0012_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
