# Generated by Django 2.2.6 on 2019-10-26 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0013_auto_20191026_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='slingshot.User'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='slingshot.Team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slingshot.User'),
        ),
    ]
