# Generated by Django 2.2.6 on 2019-10-26 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0014_auto_20191026_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tour_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_game', to='tourney.Game'),
        ),
    ]
