# Generated by Django 2.2.6 on 2019-10-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0016_auto_20191027_0001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
