# Generated by Django 2.2.6 on 2019-10-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0018_tournament'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
