# Generated by Django 2.2.6 on 2019-10-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0020_tournament'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
