# Generated by Django 2.2.6 on 2019-11-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0024_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='organize.Organization'),
        ),
    ]
