# Generated by Django 2.2.6 on 2019-11-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0008_team_password'),
        ('tourney', '0025_auto_20191117_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(blank=True, default=0)),
                ('loss', models.PositiveIntegerField(blank=True, default=0)),
                ('tie', models.PositiveIntegerField(blank=True, default=0)),
                ('kills', models.PositiveIntegerField(blank=True, default=0)),
                ('game', models.ManyToManyField(blank=True, related_name='game_stats', to='tourney.Game')),
                ('team', models.ManyToManyField(blank=True, related_name='team_stats', to='slingshot.Team')),
                ('user', models.ManyToManyField(blank=True, related_name='user_stats', to='slingshot.User')),
            ],
        ),
    ]
