# Generated by Django 2.2.6 on 2019-11-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0026_userstat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStat',
        ),
    ]
