# Generated by Django 2.2.6 on 2019-11-27 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0008_team_password'),
        ('tourney', '0028_gamestat'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='slingshot.Team'),
        ),
    ]
