# Generated by Django 2.2.6 on 2019-11-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0008_team_password'),
        ('tourney', '0029_gamestat_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(blank=True, max_length=20)),
                ('match_number', models.PositiveSmallIntegerField(default=0)),
                ('map_name', models.CharField(blank=True, max_length=10)),
                ('match_status', models.SmallIntegerField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('start_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(blank=True, max_length=20)),
                ('solo', models.ManyToManyField(blank=True, related_name='solo_stage', to='slingshot.User')),
                ('team', models.ManyToManyField(blank=True, related_name='team_stage', to='slingshot.Team')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourney_stage', to='tourney.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveSmallIntegerField(blank=True)),
                ('wins', models.PositiveSmallIntegerField(blank=True)),
                ('loss', models.PositiveSmallIntegerField(blank=True)),
                ('tie', models.PositiveSmallIntegerField(blank=True)),
                ('in_game_rank', models.PositiveSmallIntegerField(blank=True)),
                ('points', models.PositiveSmallIntegerField(blank=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_score_card', to='tourney.Match')),
                ('solo', models.ManyToManyField(blank=True, related_name='solo_score_card', to='slingshot.User')),
                ('team', models.ManyToManyField(blank=True, related_name='team_score_card', to='slingshot.User')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('solo', models.ManyToManyField(blank=True, related_name='solo_round', to='slingshot.User')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_round', to='tourney.Stage')),
                ('team', models.ManyToManyField(blank=True, related_name='team_round', to='slingshot.Team')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourney_round', to='tourney.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='round_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_match', to='tourney.Round'),
        ),
        migrations.AddField(
            model_name='match',
            name='solo',
            field=models.ManyToManyField(blank=True, related_name='solo_match', to='slingshot.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_match', to='tourney.Stage'),
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='team_match', to='slingshot.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourney_match', to='tourney.Tournament'),
        ),
    ]
