# Generated by Django 2.2.6 on 2019-11-28 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0008_team_password'),
        ('tourney', '0030_auto_20191128_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='games_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='solo',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='solo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solo_score_card', to='slingshot.User'),
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_score_card', to='slingshot.Team'),
        ),
    ]
