# Generated by Django 2.2.6 on 2019-11-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0031_auto_20191128_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='total_participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
