# Generated by Django 2.2.6 on 2019-11-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0033_auto_20191128_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
