# Generated by Django 2.2.6 on 2020-01-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0035_auto_20200117_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='desc',
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
