# Generated by Django 2.2.6 on 2020-01-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0037_auto_20200117_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
