# Generated by Django 2.2.6 on 2020-01-23 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0039_remove_tournament_start_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='place_1',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='place_10',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='place_2',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='place_3',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='place_5',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='place_6',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='place_7',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='place_8',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='place_9',
        ),
        migrations.AddField(
            model_name='tournament',
            name='prizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_prizes', to='tourney.Prize'),
        ),
    ]
