# Generated by Django 2.2.6 on 2020-01-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0040_auto_20200123_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='prizes',
        ),
        migrations.AddField(
            model_name='tournament',
            name='prizes',
            field=models.ManyToManyField(blank=True, related_name='tour_prizes', to='tourney.Prize'),
        ),
    ]
