# Generated by Django 2.2.6 on 2020-01-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0042_auto_20200123_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
