# Generated by Django 2.2.6 on 2020-01-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0043_prize_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.CharField(blank=True, default='Gamathon', max_length=10),
        ),
    ]
