# Generated by Django 2.2.6 on 2020-02-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0044_auto_20200123_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(default='tournament/logos/default-logo.png', upload_to='tournament/logos'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='banner',
            field=models.ImageField(default='tournament/banners/default-banner.jpg', upload_to='tournament/banners'),
        ),
    ]
