# Generated by Django 2.2.6 on 2020-02-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0045_auto_20200209_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.CharField(blank=True, default='Gamathon', max_length=20),
        ),
    ]
