# Generated by Django 2.2.6 on 2020-02-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0046_auto_20200215_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='sponsor_logo',
            field=models.ImageField(default='tournament/sponsors/default-sponsor-logo.png', upload_to='tournament/logos'),
        ),
    ]
