# Generated by Django 2.2.6 on 2020-02-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0047_tournament_sponsor_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='sponsor_logo',
        ),
    ]
