# Generated by Django 2.2.6 on 2020-02-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0048_remove_tournament_sponsor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='organizer_logo',
            field=models.ImageField(default='tournament/organizers/organizer-logo.png', upload_to='tournament/organizers'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sponsor_logo',
            field=models.ImageField(default='tournament/sponsors/sponsor-logo.png', upload_to='tournament/sponsors'),
        ),
    ]
