# Generated by Django 2.2.6 on 2020-02-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0049_auto_20200219_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.TextField(blank=True, max_length=50000),
        ),
    ]
