# Generated by Django 2.2.6 on 2020-02-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0050_auto_20200220_2017'),
        ('tourney', '0050_auto_20200220_2019'),
    ]

    operations = [
    ]
