# Generated by Django 2.2.6 on 2020-02-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0050_auto_20200220_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='total_participants',
        ),
    ]
