# Generated by Django 2.2.6 on 2020-02-24 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0051_remove_round_total_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourney_scorecard', to='tourney.Tournament'),
        ),
    ]
