# Generated by Django 2.2.6 on 2020-02-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0052_scorecard_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='in_game_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='kills',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='loss',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='tie',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
