# Generated by Django 2.2.6 on 2020-02-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0054_auto_20200229_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
