# Generated by Django 2.2.6 on 2020-02-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0055_gamestat_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='deaths',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
