# Generated by Django 2.2.6 on 2020-02-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slingshot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytm_no', models.CharField(blank=True, max_length=12)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('team', models.ManyToManyField(blank=True, related_name='team_withdrawal', to='slingshot.Team')),
                ('username', models.ManyToManyField(blank=True, related_name='user_withdrawal', to='slingshot.User')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('team', models.ManyToManyField(blank=True, related_name='team_deposit', to='slingshot.Team')),
                ('username', models.ManyToManyField(blank=True, related_name='user_deposit', to='slingshot.User')),
            ],
        ),
    ]
