# Generated by Django 2.2.6 on 2019-10-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawals',
            name='paytm_no',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
