# Generated by Django 2.2.6 on 2019-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slingshot', '0001_initial'),
        ('wallet', '0002_auto_20191029_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='team',
        ),
        migrations.AddField(
            model_name='deposit',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='team_deposit', to='slingshot.Team'),
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='username',
        ),
        migrations.AddField(
            model_name='deposit',
            name='username',
            field=models.ManyToManyField(blank=True, related_name='user_deposit', to='slingshot.User'),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='paytm_no',
            field=models.CharField(default=True, max_length=12),
        ),
        migrations.RemoveField(
            model_name='withdrawals',
            name='team',
        ),
        migrations.AddField(
            model_name='withdrawals',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='team_withdrawal', to='slingshot.Team'),
        ),
        migrations.RemoveField(
            model_name='withdrawals',
            name='username',
        ),
        migrations.AddField(
            model_name='withdrawals',
            name='username',
            field=models.ManyToManyField(blank=True, related_name='user_withdrawal', to='slingshot.User'),
        ),
    ]
