# Generated by Django 2.2.6 on 2020-01-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20191029_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='paytm_no',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
