# Generated by Django 2.2.6 on 2020-01-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20200119_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderid',
            name='order',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
